services:
  - docker:dind

stages:
  - build
  - test

variables:
  JAVA_HOME: "/usr/local/openjdk-17"

build-job:
  stage: build
  image: docker:23.0.5
  script:
    - docker images
    - export JAVA_HOME=$JAVA_HOME
    - $JAVA_HOME/bin/java -version
    - ./gradlew clean build --no-build-cache

test-job:
  stage: test
  image: openjdk:17-jdk
  script:
    - docker images
    - docker ps
    - export JAVA_HOME=$JAVA_HOME
    - $JAVA_HOME/bin/java -version
    - ./gradlew test
