services:
  - docker:dind

stages:
  - build
  - test

variables:
  JAVA_HOME: "/usr/local/openjdk-17"

build-job:
  stage: build
  image: adoptopenjdk:17-jdk-hotspot
  script:
    - docker images
    - java -version
    - ./gradlew clean build --no-build-cache

test-job:
  stage: test
  image: adoptopenjdk:17-jdk-hotspot
  script:
    - docker images
    - docker ps
    - java -version
    - ./gradlew test
