# services:
#   - docker:dind

stages:
  - build
  - test
  - docker

build-job:
  stage: build
  image: gradle:8.1.1-jdk17
  script:
    - ./gradlew clean build --no-build-cache
  artifacts: 
    paths: 
      - ./build/libs/

test-job:
  stage: test
  image: gradle:8.1.1-jdk17
  services:
    - mysql:latest
  script:
    - ./gradlew test

docker-build:
  stage: docker
  image: docker:23.0.6
  services:
    - docker:23.0.6-dind
  script:
    - docker build -t $CI_REGISTRY_IMAGE .
