stages:
  - build
  # - test

variables:
  JAVA_HOME: "/usr/lib/jvm/java-17-openjdk-amd64"

build-job:
  stage: build
  script:
    - export JAVA_HOME=$JAVA_HOME
    # - $JAVA_HOME/bin/java -version
    - ./gradlew clean build --no-build-cache
  # artifacts: 
  #   paths: 
  #     - /home/gitlab-runner/

# test-job:
#   stage: test
#   script:
#     - export JAVA_HOME=$JAVA_HOME
#     - $JAVA_HOME/bin/java -version
#     - ./gradlew test
