# services:
#   - docker:dind

stages:
  - build
  - test
  - docker

build-job:
  stage: build
  image: gradle:8.1.1-jdk17
  variables:
    MYSQL_ROOT_PASSWORD: my-secret-pw
  services:
    - mysql:latest
  script:
    - ./gradlew clean build --no-build-cache -Dspring.profiles.active=gitlab
  artifacts: 
    paths: 
      - ./build/libs/

# test-job:
#   stage: test
#   image: gradle:8.1.1-jdk17
#   script:
#     - ./gradlew test

docker-build:
  stage: docker
  image: docker:23.0.6
  services:
    - docker:23.0.6-dind
  script:
    - docker build -t $CI_REGISTRY_IMAGE .
