services:
  - docker:dind

stages:
  - build
  - test

variables:
  JAVA_HOME: "/usr/lib/jvm/java-17-openjdk-amd64"

build-job:
  stage: build
  script:
    - docker images
    - export JAVA_HOME=$JAVA_HOME
    - $JAVA_HOME/bin/java -version
    - ./gradlew clean build --no-build-cache

test-job:
  stage: test
  script:
    - docker images
    - docker ps
    - export JAVA_HOME=$JAVA_HOME
    - $JAVA_HOME/bin/java -version
    - ./gradlew test
