name: Build and Test

on: [push]

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Set up MySQL service
        uses: mysql/setup-mysql@v2
        with:
          mysql-version: 'latest'
          mysql-root-password: ${{ secrets.MYSQL_ROOT_PASSWORD }}

      - name: Build with Gradle
        run: ./gradlew clean build --no-build-cache -Dspring.profiles.active=dev

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Build artifacts
          path: ./build/libs/
